name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Jak II Hot Rod"
      metadataDescription: "Changes one of the overworld zoomers to always spawn as a hot rod variant. Max speed has been increased from 40 to 200."
      metadataSupportedGames: "jak2"
      metadataAuthors: "Ruh"
      metadataTags: "texture-mod,gameplay-mod"
      metadataWebsiteUrl: "https://github.com/rileyfort/jak-2-hot-rod/blob/main/README.md"
      skipMacOS: true
      skipLinux: true
      toolingBinaryDir: "out/build/Release/bin"
      gameAssetsDir: "game/assets"
      copyEntireBinaryDir: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
